Exception on /chat/ [POST]
Traceback (most recent call last):
  File "/home/power/anaconda3/envs/flask/lib/python3.9/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/power/anaconda3/envs/flask/lib/python3.9/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/power/anaconda3/envs/flask/lib/python3.9/site-packages/flask_cors/extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/power/anaconda3/envs/flask/lib/python3.9/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/power/anaconda3/envs/flask/lib/python3.9/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/power/flask/./app/controller/chats.py", line 16, in chat_message
    res = chat_service.chat_with_agent(data.get('message'))
  File "/home/power/flask/./app/service/chat_service.py", line 5, in chat_with_agent
    res = agent.get_agent().invoke(input = {'promble': user_input})
  File "/home/power/flask/./chain/agent.py", line 52, in get_agent
    return prompt.get_prompt() | model.get_model() | output_parser.get_parser
NameError: name 'prompt' is not defined
